---
- import_tasks: install_packages.yml
  when: packages_installed is defined and not packages_installed

- name: Create export directories
  ansible.builtin.file:
    path: "{{ base_dir }}{{ item }}"
    state: directory
    mode: '0777'
  loop: "{{ range(number_exports) }}"

- name: Configure the exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ item }}"
  loop: "{{ list_of_shares }}"
